In [2]:
import pandas as pd


In [6]:
pwd

'C:\\Users\\Alumno\\clase 27-04'

In [8]:
ls

 El volumen de la unidad C no tiene etiqueta.
 El número de serie del volumen es: 463B-22B5

 Directorio de C:\Users\Alumno\clase 27-04

27/04/2022  20:05    <DIR>          .
27/04/2022  20:05    <DIR>          ..
27/04/2022  20:03    <DIR>          .ipynb_checkpoints
27/04/2022  20:05             3.075 Untitled.ipynb
               1 archivos          3.075 bytes
               3 dirs  32.692.146.176 bytes libres


In [9]:
cd ..

C:\Users\Alumno


In [12]:
ls

 El volumen de la unidad C no tiene etiqueta.
 El número de serie del volumen es: 463B-22B5

 Directorio de C:\Users\Alumno

27/04/2022  20:03    <DIR>          .
27/04/2022  20:03    <DIR>          ..
10/12/2021  17:15    <DIR>          .android
27/04/2022  20:08    <DIR>          .conda
27/04/2022  19:59                25 .condarc
27/04/2022  19:59    <DIR>          .continuum
25/04/2022  19:15    <DIR>          .docker
07/12/2021  17:49    <DIR>          .dotnet
27/04/2022  20:03    <DIR>          .ipython
27/04/2022  19:59    <DIR>          .jupyter
09/12/2021  17:55    <DIR>          .mchp_packs
09/12/2021  17:55    <DIR>          .mplabcomm
07/12/2021  18:36    <DIR>          .nbi
27/04/2022  10:30    <DIR>          .ssh
27/04/2022  20:03             7.327 2022-04-26.rar
07/12/2021  12:03    <DIR>          3D Objects
07/12/2021  18:21    <DIR>          Anaconda3
27/04/2022  09:15               717 ARTICULOS.CSV
09/12/2021  19:12    <DIR>          Autodesk
27/04/2022  20:07    <DI

In [13]:
cd Downloads

C:\Users\Alumno\Downloads


In [14]:
ls

 El volumen de la unidad C no tiene etiqueta.
 El número de serie del volumen es: 463B-22B5

 Directorio de C:\Users\Alumno\Downloads

27/04/2022  19:56    <DIR>          .
27/04/2022  19:56    <DIR>          ..
27/04/2022  19:56            89.232 diabetes_completo.csv
25/04/2022  19:01       523.594.696 Docker Desktop Installer.exe
27/04/2022  19:51       124.383.891 pack mejorado.rar
26/04/2022  12:44    <DIR>          pryBonaderoTP3Interfaces
26/04/2022  11:56            22.042 pryBonaderoTP3Interfaces.rar
               4 archivos    648.089.861 bytes
               3 dirs  32.691.085.312 bytes libres


In [17]:
pwd


'C:\\Users\\Alumno\\Downloads'

In [22]:
df= pd.read_csv("C:\\Users\\Alumno\\Downloads\\diabetes_completo.csv")
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   x1      5 non-null      float64
 1   x2      5 non-null      float64
 2   x3      5 non-null      float64
 3   x4      5 non-null      float64
 4   x5      5 non-null      float64
 5   x6      5 non-null      float64
 6   x7      5 non-null      float64
 7   x8      5 non-null      float64
 8   x9      5 non-null      float64
 9   x10     5 non-null      float64
 10  y       5 non-null      float64
dtypes: float64(11)
memory usage: 568.0 bytes


In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   x1      442 non-null    float64
 1   x2      442 non-null    float64
 2   x3      442 non-null    float64
 3   x4      442 non-null    float64
 4   x5      442 non-null    float64
 5   x6      442 non-null    float64
 6   x7      442 non-null    float64
 7   x8      442 non-null    float64
 8   x9      442 non-null    float64
 9   x10     442 non-null    float64
 10  y       442 non-null    float64
dtypes: float64(11)
memory usage: 38.1 KB


In [51]:
import numpy as np
a=df.y.unique()
a

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144., 168.,  68.,  49., 245.,
       184., 202., 137.,  85., 131., 283., 129.,  59., 341.,  87.,  65.,
       102., 265., 276., 252.,  90., 100.,  55.,  61.,  92., 259.,  53.,
       190., 142., 155., 225., 104., 182., 128.,  52.,  37., 170.,  71.,
       163., 150., 160., 178.,  48., 270., 111.,  42., 200., 113., 143.,
        51., 210., 134.,  98., 164.,  96., 162., 279.,  83., 302., 198.,
        95., 232.,  81., 246., 297., 258., 229., 275., 281., 173., 180.,
        84., 121., 161.,  99., 109., 115., 268., 274., 158., 107., 103.,
       272., 280., 336., 317., 235.,  60., 174., 126., 288.,  88., 292.,
       197., 186.,  25., 195., 217., 172., 214.,  70., 220., 152.,  47.,
        74., 295., 127., 237.,  64.,  79.,  91., 116.,  86., 122.,  72.,
        39., 196., 222., 277.,  77., 191.,  73., 263., 248., 296.,  78.,
        93., 208., 108., 154., 124.,  67., 257., 26

In [55]:
a.count()

AttributeError: 'numpy.ndarray' object has no attribute 'count'

In [53]:
from sklearn.model_selection import train_test_split

In [54]:
train,test= train_test_split(df,test_size=0.2,random_state=123)

In [29]:
train

x1        x2        x3        x4        x5        x6        x7  \
59   0.063504  0.050680 -0.025607  0.011544  0.064477  0.048477  0.030232   
209  0.038076  0.050680 -0.018062  0.066630 -0.051103 -0.016658 -0.076536   
21  -0.085430  0.050680 -0.022373  0.001215 -0.037344 -0.026366  0.015505   
274  0.016281 -0.044642 -0.024529  0.035644 -0.007073 -0.003193 -0.013948   
107  0.027178 -0.044642  0.049840 -0.055018 -0.002945  0.040648 -0.058127   
..        ...       ...       ...       ...       ...       ...       ...   
230 -0.038207  0.050680  0.071397 -0.057314  0.153914  0.155887  0.000779   
98   0.001751  0.050680 -0.005128 -0.012556 -0.015328 -0.013840  0.008142   
322  0.023546  0.050680  0.061696  0.062039  0.024574 -0.036073 -0.091262   
382  0.048974 -0.044642  0.060618 -0.022885 -0.023584 -0.072712 -0.043401   
365  0.034443 -0.044642 -0.038540 -0.012556  0.009439  0.005262 -0.006584   

           x8        x9       x10      y  
59  -0.002592  0.038393  0.019633  170.0  
209  0.034309 -0.011901 -0.013504   77.0  
21  -0.039493 -0.072128 -0.017646   49.0  
274 -0.002592  0.015567  0.015491   66.0  
107  0.052759 -0.052959 -0.005220  144.0  
..        ...       ...       ...    ...  
230  0.071948  0.050276  0.069338  220.0  
98  -0.039493 -0.006080 -0.067351   92.0  
322  0.155345  0.133396  0.081764  242.0  
382 -0.002592  0.104138  0.036201  132.0  
365 -0.002592  0.031193  0.098333  206.0  

[353 rows x 11 columns]

In [30]:
test

x1        x2        x3        x4        x5        x6        x7  \
13   0.005383  0.050680 -0.001895  0.008101 -0.004321 -0.015719 -0.002903   
66  -0.009147  0.050680 -0.018062 -0.033214 -0.020832  0.012152 -0.072854   
234  0.045341 -0.044642  0.039062  0.045972  0.006687 -0.024174  0.008142   
24  -0.063635 -0.044642  0.035829 -0.022885 -0.030464 -0.018850 -0.006584   
388  0.052606  0.050680 -0.024529  0.056301 -0.007073 -0.005072 -0.021311   
..        ...       ...       ...       ...       ...       ...       ...   
114  0.023546 -0.044642  0.110198  0.063187  0.013567 -0.032942 -0.024993   
142  0.041708  0.050680  0.012117  0.039087  0.054845  0.044406  0.004460   
121  0.063504 -0.044642  0.017506  0.021872  0.008063  0.021546 -0.036038   
31  -0.023677 -0.044642 -0.065486 -0.081414 -0.038720 -0.053610  0.059685   
385  0.023546  0.050680 -0.019140  0.049415 -0.063487 -0.061125  0.004460   

           x8        x9       x10      y  
13  -0.002592  0.038393 -0.013504  185.0  
66   0.071210  0.000271  0.019633  150.0  
234 -0.012556  0.064328  0.056912  246.0  
24  -0.002592 -0.025952 -0.054925  184.0  
388 -0.002592  0.026714 -0.038357  110.0  
..        ...       ...       ...    ...  
114  0.020655  0.099240  0.023775  258.0  
142 -0.002592  0.045601 -0.001078  235.0  
121  0.034309  0.019908  0.011349  173.0  
31  -0.076395 -0.037128 -0.042499   59.0  
385 -0.039493 -0.025952 -0.013504  219.0  

[89 rows x 11 columns]

In [33]:
train_x= train.drop(["y"], axis=1)
train_y= train.y
test_x= test.drop(["y"], axis=1)
test_y= test.y

In [34]:
train_x

x1        x2        x3        x4        x5        x6        x7  \
59   0.063504  0.050680 -0.025607  0.011544  0.064477  0.048477  0.030232   
209  0.038076  0.050680 -0.018062  0.066630 -0.051103 -0.016658 -0.076536   
21  -0.085430  0.050680 -0.022373  0.001215 -0.037344 -0.026366  0.015505   
274  0.016281 -0.044642 -0.024529  0.035644 -0.007073 -0.003193 -0.013948   
107  0.027178 -0.044642  0.049840 -0.055018 -0.002945  0.040648 -0.058127   
..        ...       ...       ...       ...       ...       ...       ...   
230 -0.038207  0.050680  0.071397 -0.057314  0.153914  0.155887  0.000779   
98   0.001751  0.050680 -0.005128 -0.012556 -0.015328 -0.013840  0.008142   
322  0.023546  0.050680  0.061696  0.062039  0.024574 -0.036073 -0.091262   
382  0.048974 -0.044642  0.060618 -0.022885 -0.023584 -0.072712 -0.043401   
365  0.034443 -0.044642 -0.038540 -0.012556  0.009439  0.005262 -0.006584   

           x8        x9       x10  
59  -0.002592  0.038393  0.019633  
209  0.034309 -0.011901 -0.013504  
21  -0.039493 -0.072128 -0.017646  
274 -0.002592  0.015567  0.015491  
107  0.052759 -0.052959 -0.005220  
..        ...       ...       ...  
230  0.071948  0.050276  0.069338  
98  -0.039493 -0.006080 -0.067351  
322  0.155345  0.133396  0.081764  
382 -0.002592  0.104138  0.036201  
365 -0.002592  0.031193  0.098333  

[353 rows x 10 columns]

In [35]:
test_x

x1        x2        x3        x4        x5        x6        x7  \
13   0.005383  0.050680 -0.001895  0.008101 -0.004321 -0.015719 -0.002903   
66  -0.009147  0.050680 -0.018062 -0.033214 -0.020832  0.012152 -0.072854   
234  0.045341 -0.044642  0.039062  0.045972  0.006687 -0.024174  0.008142   
24  -0.063635 -0.044642  0.035829 -0.022885 -0.030464 -0.018850 -0.006584   
388  0.052606  0.050680 -0.024529  0.056301 -0.007073 -0.005072 -0.021311   
..        ...       ...       ...       ...       ...       ...       ...   
114  0.023546 -0.044642  0.110198  0.063187  0.013567 -0.032942 -0.024993   
142  0.041708  0.050680  0.012117  0.039087  0.054845  0.044406  0.004460   
121  0.063504 -0.044642  0.017506  0.021872  0.008063  0.021546 -0.036038   
31  -0.023677 -0.044642 -0.065486 -0.081414 -0.038720 -0.053610  0.059685   
385  0.023546  0.050680 -0.019140  0.049415 -0.063487 -0.061125  0.004460   

           x8        x9       x10  
13  -0.002592  0.038393 -0.013504  
66   0.071210  0.000271  0.019633  
234 -0.012556  0.064328  0.056912  
24  -0.002592 -0.025952 -0.054925  
388 -0.002592  0.026714 -0.038357  
..        ...       ...       ...  
114  0.020655  0.099240  0.023775  
142 -0.002592  0.045601 -0.001078  
121  0.034309  0.019908  0.011349  
31  -0.076395 -0.037128 -0.042499  
385 -0.039493 -0.025952 -0.013504  

[89 rows x 10 columns]

In [37]:
test_y


13     185.0
66     150.0
234    246.0
24     184.0
388    110.0
       ...  
114    258.0
142    235.0
121    173.0
31      59.0
385    219.0
Name: y, Length: 89, dtype: float64

In [70]:
from sklearn import linear_model
modelo = linear_model.LinearRegression()

In [71]:
modelo

LinearRegression()

In [72]:
modelo.fit(train_x,train_y)

LinearRegression()

In [73]:
precision= modelo.score(train_x,train_y)
precision

0.5015524096207558

In [62]:
modelo.predict(test_x)

array([162.26359467, 155.48747839, 227.01019671, 164.63583097,
       158.78861876, 135.27411288, 253.95946355, 106.30662813,
       103.03631134, 114.33330776, 123.87775522, 183.76354732,
       163.00541455, 203.26084844, 214.91810729, 174.49695156,
       108.43475278, 145.38313077, 175.78816988, 191.42525183,
       164.57232464, 233.24090956, 140.03825949,  73.79751056,
       129.98678458, 189.7593074 ,  99.60413529,  99.22486195,
       158.34182642, 184.63831369,  81.93551519, 238.22291295,
       208.12075731, 210.13292762, 199.08373866,  94.83582711,
        93.49289059,  99.17948241, 228.27847992, 101.50596652,
       192.67553228,  81.54468369, 103.23825593, 147.13568637,
       111.39328423, 215.7577106 ,  80.45897342,  75.04534093,
       100.72245569, 217.41160041,  69.28173936, 115.45236404,
       175.51938644, 195.88993672, 139.8423833 , 197.26642367,
       220.21419051, 170.768533  , 194.81047154, 190.59958364,
       138.06597191, 121.09270082, 234.55652657, 203.16

In [64]:
test_y

13     185.0
66     150.0
234    246.0
24     184.0
388    110.0
       ...  
114    258.0
142    235.0
121    173.0
31      59.0
385    219.0
Name: y, Length: 89, dtype: float64

In [66]:
y_predict=modelo.predict(test_x)
y_predict

array([162.26359467, 155.48747839, 227.01019671, 164.63583097,
       158.78861876, 135.27411288, 253.95946355, 106.30662813,
       103.03631134, 114.33330776, 123.87775522, 183.76354732,
       163.00541455, 203.26084844, 214.91810729, 174.49695156,
       108.43475278, 145.38313077, 175.78816988, 191.42525183,
       164.57232464, 233.24090956, 140.03825949,  73.79751056,
       129.98678458, 189.7593074 ,  99.60413529,  99.22486195,
       158.34182642, 184.63831369,  81.93551519, 238.22291295,
       208.12075731, 210.13292762, 199.08373866,  94.83582711,
        93.49289059,  99.17948241, 228.27847992, 101.50596652,
       192.67553228,  81.54468369, 103.23825593, 147.13568637,
       111.39328423, 215.7577106 ,  80.45897342,  75.04534093,
       100.72245569, 217.41160041,  69.28173936, 115.45236404,
       175.51938644, 195.88993672, 139.8423833 , 197.26642367,
       220.21419051, 170.768533  , 194.81047154, 190.59958364,
       138.06597191, 121.09270082, 234.55652657, 203.16

In [75]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

In [95]:
r2_score(test_y, y_predict)
print("R2: ",round(r2_score(test_y, y_predict),3))

R2:  0.568


In [93]:
mean_squared_error(test_y,y_predict)
print("MSE: ", round(mean_squared_error(test_y,y_predict),3))

MSE:  2724.245


In [94]:
mean_squared_error(test_y,y_predict)
print("MSE: ", round(mean_squared_error(test_y,y_predict,squared=False),3))

MSE:  52.194


In [109]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
df= pd.read_csv("C:\\Users\\Alumno\\Downloads\\diabetes_completo.csv")
train,test= train_test_split(df,test_size=0.2,random_state=123)
train_x= train.drop(["y"], axis=1)
train_y= train.y
test_x= test.drop(["y"], axis=1)
test_y= test.y
modelo = linear_model.LinearRegression()
modelo.fit(train_x,train_y)
y_predict=modelo.predict(test_x)
y_predict

print("R2: ",(r2_score(test_y, y_predict))) 
#print("MSE: ", round(mean_squared_error(test_y,y_predict),3))
#print("RMSE: ", round(mean_squared_error(test_y,y_predict,squared=False),3))

R2:  0.5675916622351821


In [110]:
test_y

13     185.0
66     150.0
234    246.0
24     184.0
388    110.0
       ...  
114    258.0
142    235.0
121    173.0
31      59.0
385    219.0
Name: y, Length: 89, dtype: float64