In [41]:
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [42]:
df = pd.read_csv("/content/drive/MyDrive/Inteligencia Artificial/segundo año/primer semestre/Practica Profecionalizante 1/tp/presion maxima TP2/DataSet Edad-Talla-Peso-TA.csv", sep=';',decimal=',')
df

Altura   Peso Sexo  Edad  PA_max
0       1.47  53000    M    33    12.3
1     172.00     90    F    28    13.3
2       1.60    118    M    77    24.9
3       1.76     97    M    52    18.3
4       1.81    118    F    73    25.8
...      ...    ...  ...   ...     ...
4995    1.85    105    M    74    13.6
4996    1.78     66    F    31     9.9
4997    1.81    168    F    57    15.5
4998    2.04     99    M    44    11.8
4999    1.82     99    M    74    19.3

[5000 rows x 5 columns]

### Veo si las columnas están cargadas correctamente o con errores en unidades de medida

Para la unidad de medida de Presion Arterial maxima, están mescladas las unidades mmHg y cmHg

In [43]:
np.sort(df['PA_max'].unique())

array([  8.4,   8.5,   8.6,   8.7,   8.8,   9. ,   9.1,   9.2,   9.3,
         9.4,   9.5,   9.6,   9.7,   9.8,   9.9,  10. ,  10.1,  10.2,
        10.3,  10.4,  10.5,  10.6,  10.7,  10.8,  10.9,  11. ,  11.1,
        11.2,  11.3,  11.4,  11.5,  11.6,  11.7,  11.8,  11.9,  12. ,
        12.1,  12.2,  12.3,  12.4,  12.5,  12.6,  12.7,  12.8,  12.9,
        13. ,  13.1,  13.2,  13.3,  13.4,  13.5,  13.6,  13.7,  13.8,
        13.9,  14. ,  14.1,  14.2,  14.3,  14.4,  14.5,  14.6,  14.7,
        14.8,  14.9,  15. ,  15.1,  15.2,  15.3,  15.4,  15.5,  15.6,
        15.7,  15.8,  15.9,  16. ,  16.1,  16.2,  16.3,  16.4,  16.5,
        16.6,  16.7,  16.8,  16.9,  17. ,  17.1,  17.2,  17.3,  17.4,
        17.5,  17.6,  17.7,  17.8,  17.9,  18. ,  18.1,  18.2,  18.3,
        18.4,  18.5,  18.6,  18.7,  18.8,  18.9,  19. ,  19.1,  19.2,
        19.3,  19.4,  19.5,  19.6,  19.7,  19.8,  19.9,  20. ,  20.1,
        20.2,  20.3,  20.4,  20.5,  20.6,  20.7,  20.8,  20.9,  21. ,
        21.1,  21.2,

En la categoria Sexo tenemos datos sin cargar

In [44]:
df['Sexo'].unique()

array(['M', 'F', nan], dtype=object)

En edad parece estar todo correctamente

In [45]:
np.sort(df['Edad'].unique())

array([18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77])

En La variable altura, está mezclada la unidad de medida de cm con la de metro y tenemos datos nulos

In [46]:
np.sort(df['Altura'].unique())

array([  1.45,   1.46,   1.47,   1.48,   1.49,   1.5 ,   1.51,   1.52,
         1.53,   1.54,   1.55,   1.56,   1.57,   1.58,   1.59,   1.6 ,
         1.61,   1.62,   1.63,   1.64,   1.65,   1.66,   1.67,   1.68,
         1.69,   1.7 ,   1.71,   1.72,   1.73,   1.74,   1.75,   1.76,
         1.77,   1.78,   1.79,   1.8 ,   1.81,   1.82,   1.83,   1.84,
         1.85,   1.86,   1.87,   1.88,   1.89,   1.9 ,   1.91,   1.92,
         1.93,   1.94,   1.95,   1.96,   1.97,   1.98,   1.99,   2.  ,
         2.01,   2.02,   2.03,   2.04,   2.05,   2.06,   2.07,   2.08,
         2.09,   2.1 ,   2.11,   2.12,   2.13,   2.14,   2.15,   2.27,
         2.28,   2.35, 145.  , 146.  , 148.  , 149.  , 151.  , 152.  ,
       155.  , 157.  , 158.  , 160.  , 161.  , 163.  , 164.  , 166.  ,
       167.  , 169.  , 170.  , 172.  , 173.  , 175.  , 176.  , 178.  ,
       179.  , 181.  , 182.  , 184.  , 185.  , 187.  , 188.  , 190.  ,
       191.  , 193.  , 194.  , 196.  , 199.  , 200.  , 203.  , 205.  ,
      

En la variable Peso, está mezclada la unidad de medida de gramos y kg, y contiene datos nulos=0

In [47]:
np.sort(df['Peso'].unique())

array([     0,     36,     37,     38,     39,     40,     41,     42,
           43,     44,     45,     46,     47,     48,     49,     50,
           51,     52,     53,     54,     55,     56,     57,     58,
           59,     60,     61,     62,     63,     64,     65,     66,
           67,     68,     69,     70,     71,     72,     73,     74,
           75,     76,     77,     78,     79,     80,     81,     82,
           83,     84,     85,     86,     87,     88,     89,     90,
           91,     92,     93,     94,     95,     96,     97,     98,
           99,    100,    101,    102,    103,    104,    105,    106,
          107,    108,    109,    110,    111,    112,    113,    114,
          115,    116,    117,    118,    119,    120,    121,    122,
          123,    124,    125,    126,    127,    128,    129,    130,
          131,    132,    133,    134,    135,    136,    137,    138,
          139,    140,    141,    142,    143,    144,    145,    146,
      

### Empiezo a corregir las unidades 

In [48]:
#Genero una copia del Set de datos original para así poder modificarlo a mi gusto
dfcorregido=df.copy()
#Corrijo los datos, cambiando las unidades de medida si es necesario
dfcorregido['Altura'].loc[dfcorregido['Altura'] >= 3.0] = (dfcorregido['Altura']/100)
dfcorregido['Peso'].loc[dfcorregido['Peso'] >= 600] = (dfcorregido['Peso']/1000)
dfcorregido['PA_max'].loc[dfcorregido['PA_max'] >= 33] = (dfcorregido['PA_max']/10)
#Reemplazo los valores nulos cargados como 0 a np.nan
dfcorregido=dfcorregido.replace(0,np.nan)
dfcorregido

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



Altura   Peso Sexo  Edad  PA_max
0       1.47   53.0    M    33    12.3
1       1.72   90.0    F    28    13.3
2       1.60  118.0    M    77    24.9
3       1.76   97.0    M    52    18.3
4       1.81  118.0    F    73    25.8
...      ...    ...  ...   ...     ...
4995    1.85  105.0    M    74    13.6
4996    1.78   66.0    F    31     9.9
4997    1.81  168.0    F    57    15.5
4998    2.04   99.0    M    44    11.8
4999    1.82   99.0    M    74    19.3

[5000 rows x 5 columns]

### Genero la Columna de IMC

In [49]:
#IMC es igual a peso/altura^2
dfcorregido['IMC']= (dfcorregido['Peso']/(dfcorregido['Altura']**2)).round(2)
dfcorregido

Altura   Peso Sexo  Edad  PA_max    IMC
0       1.47   53.0    M    33    12.3  24.53
1       1.72   90.0    F    28    13.3  30.42
2       1.60  118.0    M    77    24.9  46.09
3       1.76   97.0    M    52    18.3  31.31
4       1.81  118.0    F    73    25.8  36.02
...      ...    ...  ...   ...     ...    ...
4995    1.85  105.0    M    74    13.6  30.68
4996    1.78   66.0    F    31     9.9  20.83
4997    1.81  168.0    F    57    15.5  51.28
4998    2.04   99.0    M    44    11.8  23.79
4999    1.82   99.0    M    74    19.3  29.89

[5000 rows x 6 columns]

### Analizo mi DataFrame y genero mi matriz de correlacion

In [50]:
# Veo la cantidad de datos nulos que tengo
dfcorregido.isnull().sum()

Altura     99
Peso       33
Sexo       90
Edad        0
PA_max      0
IMC       131
dtype: int64

In [51]:
#Con .describe() obtengo los promedios de cada variable en este estudio, ademas de ver los valores minimos y maximos,
# y las columnas que tienen datos faltantes.
dfcorregido.describe().round(2)

Altura     Peso     Edad   PA_max      IMC
count  4901.00  4967.00  5000.00  5000.00  4869.00
mean      1.71    88.10    47.88    15.02    29.81
std       0.14    34.21    17.30     3.58     9.50
min       1.45    36.00    18.00     8.40    17.12
25%       1.60    64.00    33.00    12.50    23.11
50%       1.69    80.00    48.00    14.40    27.17
75%       1.80   102.00    63.00    16.70    31.85
max       2.35   289.00    77.00    32.30    65.51

In [52]:
df_Corr= dfcorregido.corr()
df_Corr.round(2)

Altura  Peso  Edad  PA_max   IMC
Altura    1.00  0.55  0.02    0.09  0.15
Peso      0.55  1.00  0.02    0.14  0.89
Edad      0.02  0.02  1.00    0.42  0.00
PA_max    0.09  0.14  0.42    1.00  0.13
IMC       0.15  0.89  0.00    0.13  1.00

De la matriz de correlacion podemos sacar las siguientes conclusiones:
*   Altura: Relacion directa con peso, sin relacion con edad, sin relacion con Presion maxima y sin relacion con IMC
*   Peso: Relacion directa con Altura, sin relacion con edad, poca con Presion maxima y Relacion directa con IMC
*   Edad: sin relacion con Altura, sin relacion con Peso, Relacion directa con Presion maxima, sin relacion con IMC
*   PA_max: sin relacion con Altura, sin relacion con Peso, Relacion directa con Edad, sin relacion con IMC
*   IMC: sin relacion con Altura, Relacion directa con Peso, sin relacion con Edad, Sin relacion con Presion maxima



### Graficas

**Proporcion de Hombres y Mujeres en el estudio**

In [64]:
# Creo variables dummy (0,1) para la columna sexo ya que es categorica
sexo_dummy = pd.get_dummies(dfcorregido['Sexo'], prefix='sexo')
# Para sacar la cantidad total de hombres y mujeres, sumo todos los 1 de cada columna y lo guardo en variables para luego generar un diccionario con estas
x=sexo_dummy['sexo_F'].sum()
y= sexo_dummy['sexo_M'].sum()
datos= {
    'Genero' : ['Mujeres','Hombres'],
    'Cantidad' : [x,y]
}
# Genero un Dataframe con los datos del diccionario anterior
Df_genero= pd.DataFrame(datos)
#importo la libreria plotly para luego generar el grafico de pie
import plotly.express as px
fig = px.pie(Df_genero, values='Cantidad',names='Genero',title='Proporcion de Hombres y Mujeres en el estudio')
fig.show()

En la proporcion de hombres y mujeres, se puede ver que la proporcion de cada es parecida, por lo que los datos no quedarian sesgados si esta variable tuviese gran importancia

**Proporcion de edad en el Estudio**

In [63]:
#Genero separaciones de la edad con respecto al grupo (Juventud, adultez y vejez) para luego cargar los datos en un diccionario. En el diccionario
# debo especificar la columna, ya que cada variale es un DataFrame
Juventud=dfcorregido.loc[dfcorregido['Edad']<=29]
Edad_Adulta=dfcorregido.loc[(dfcorregido['Edad']<=59) & (dfcorregido['Edad']>=30)]
Vejez=dfcorregido.loc[dfcorregido['Edad']>=60]
datos= {
    'Etapas' : ['Juventud','Adultez','Vejez'],
    'Cantidad' : [Juventud['Edad'].count(),Edad_Adulta['Edad'].count(),Vejez['Edad'].count()]
}
#Cargo los datos del diccionario en un Dataframe vacio
Df_Edad= pd.DataFrame(datos)
#importo la libreria plotly para luego generar el grafico de pie
import plotly.express as px
fig = px.pie(Df_Edad, values='Cantidad',names='Etapas',title='Proporcion de edades en el estudio')
fig.show()

Del grafico anterior se puede observar que la mayoria de datos cargados son adultos, seguido por ancianos y la menor proporcion son jovenes 

**Analisis de IMC**

In [61]:
#Genero separaciones del IMC con respecto al grupo (Delgado, Normal, Sobrepeso, Obesidad, Obesidad morvida) para luego cargar los datos en un diccionario.
# En el diccionario debo especificar la columna, ya que cada variale es un DataFrame
Delgado=dfcorregido.loc[dfcorregido['IMC']<18.5]
Normal=dfcorregido.loc[(dfcorregido['IMC']>=18.5) & (dfcorregido['IMC']<=24.9)]
Sobrepeso=dfcorregido.loc[(dfcorregido['IMC']>=25) & (dfcorregido['IMC']<=29.9)]
Obesidad = dfcorregido.loc[(dfcorregido['IMC']>=30) & (dfcorregido['IMC']<=39.9)]
Obesidad_morvida = dfcorregido.loc[dfcorregido['IMC']>=40]
datos= {
    'Estado' : ['Delgado','Normal','Sobrepeso','Obesidad','Obesidad Morvida'],
    'Cantidad' : [Delgado['IMC'].count(),Normal['IMC'].count(),Sobrepeso['IMC'].count(),Obesidad['IMC'].count(),Obesidad_morvida['IMC'].count()]
}
#Cargo los datos del diccionario en un Dataframe vacio
Df_Edad= pd.DataFrame(datos)
#importo la libreria plotly para luego generar el grafico de pie
import plotly.express as px
fig = px.pie(Df_Edad, values='Cantidad',names='Estado',title='Estado de IMC en el estudio')
fig.show()

Del grafico anterior se puede concluir que en el analisis, el mayor porcentaje de los datos tienen el IMC normal, seguido muy de cerca por Sobrepeso, en menor proporcion se encuentra la Obesidad y seguido de cerca la Obesidad Morvida, el grupo Delgado es muy bajo, siendo solo 49 observaciones

**Proporcion de tipos de Presion Arterial maxima**

In [62]:
#Genero separaciones de PA_max con respecto al grupo (Optima, Normal, Alta, Hipertension grado 1, Hipertension grado 2, Hipertension grado 3) 
#para luego cargar los datos en un diccionario. En el diccionario debo especificar la columna, ya que cada variale es un DataFrame
Optima=dfcorregido.loc[dfcorregido['PA_max']<12]
Normal=dfcorregido.loc[(dfcorregido['PA_max']>=12) & (dfcorregido['PA_max']<13)]
Alta=dfcorregido.loc[(dfcorregido['PA_max']>=13) & (dfcorregido['PA_max']<=13.9)]
Hipertension_grado_1 = dfcorregido.loc[(dfcorregido['PA_max']>=14) & (dfcorregido['PA_max']<15.9)]
Hipertension_grado_2 = dfcorregido.loc[(dfcorregido['PA_max']>=16) & (dfcorregido['PA_max']<18)]
Hipertension_grado_3=dfcorregido.loc[dfcorregido['PA_max']>18]
datos= {
    'Categoría' : ['Optima','Normal','Alta','Hipertension_grado_1','Hipertension_grado_2', 'Hipertension_grado_3'],
    'Cantidad' : [Optima['PA_max'].count(),Normal['PA_max'].count(),Alta['PA_max'].count(),Hipertension_grado_1['PA_max'].count(),Hipertension_grado_2['PA_max'].count(),Hipertension_grado_3['PA_max'].count()]
}
#Cargo los datos del diccionario en un Dataframe vacio
Df_Edad= pd.DataFrame(datos)
#importo la libreria plotly para luego generar el grafico de pie
import plotly.express as px
fig = px.pie(Df_Edad, values='Cantidad',names='Categoría',title='Estado de PA_max')
fig.show()

**Relacion entre la edad y la Presion Arterial Maxima:**
*   Se Puede ver que a medida que la persona envejece, la Presion Arterial Maxima aumenta



In [57]:
#Para generar el grafico, especifico en nombre del DataFrame que se quiere visualizar, selecciono que columna va a ser el parametro x o y
import plotly.express as px
fig = px.histogram(dfcorregido, x="Edad", y="PA_max", histfunc='avg')
fig.show()

**Relalcion del IMC con PA_max**
* Se puede observar que hay una leve relacion entre estas variables, siendo el valor mas alto de PA_max cuando el IMC es voluminoso

In [58]:
#Para generar el grafico, especifico en nombre del DataFrame que se quiere visualizar, selecciono que columna va a ser el parametro x o y
import plotly.express as px
fig = px.histogram(dfcorregido, x="IMC", y="PA_max", histfunc='avg')
fig.show()

### Scatter en 3D

In [60]:
#Genero un DataFrame con las columnas Edad, IMC, PA_max y Sexo, las primeras tres seran los valores de x, y e z, y la variable Sexo será un separador de color
Scatter_3D = dfcorregido[['Edad','IMC','PA_max','Sexo']]
# Elimino los datos nulos, por si llegara a afectar a la grafica
Scatter_3D=Scatter_3D.dropna()
#Genero la grafica con plotly
import plotly.express as px
fig = px.scatter_3d(Scatter_3D, x='Edad', y='IMC', z='PA_max',color='Sexo') 
fig.show()

### Concusion de lo obtenido 

Como pudimos observar en los graficos obtenidos, la PA_max se ve muy influenciada con la edad, ya que a mayor edad, mayor será el valor de PA_max, pero ademas, el IMC tambien afecta al PA_max, pero no en el grado que lo hace la edad. El genero no genera grandes diferencias en la variacion de PA_max