![imagen](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRv7-9e8oYLYuPJ2mPM3YOlHoKFiHaQCFClWRKVBOzUe1CWABtg5QtluntYIxiHgpYNdw&usqp=CAU)

# Computación Científica

## Lista de datos en phyton
Las listas son conjuntos de datos que pueden contener elementos de distinto tipo, por ejemplo, texto o números y los vectores que aprendió a usar en álgebra son numéricos.

In [12]:
# Considerado una lista, puede recibir datos numericos como de tipo de texto #
a= (1,"Jorge",9)
a

(1, 'Jorge', 9)

In [14]:
# Para seleccionar un elemento de la lista basta con poner una orden print, llamando a la variable "a" y entre corchetes #z
# seleccionar el numero de la posicion de la herramienta a usar de la lista, recordando de que empieza del 0 en adelante 
a= (1,"Jorge",9)
print(a[1])

Jorge


In [19]:
# Para acceder a tablas mas extensas y seleccionar un dato solicitado se debe ingresar primero el valor de la fila y 
#luego el valor de la columna donde está este Dato
lista = ((1,"Jorge",9),(2,"Ana",10), (3,"María",11))
print( lista [1][1]) 

Ana


In [21]:
#pyhton nos permite tenér la posibilidad de que las listas no si o si deben tener la misma dimencion 
# Si se requiere que se muestre un dato en una lista que tiene menos filas que las otras dará un problema de rango 
lista = ((1,2,3), (4,5,6,7), (4,5,8,9,4))
print(lista[2][4])

4


In [45]:
# Si queremos mostrar cada numero de la lista debo crear una estructura repetitiva 
lista = (1,2,3)
for x in lista:
    print(x)

1
2
3


Pero a veces tenemos listas que contienen sólo valores numéricos y podemos confundirnos creyendo que son numeros, pero los trata como datos de tipo texto. En estos casos suelen ocurrir cosas inesperadas cuando hacemos operaciones algebraicas como la siguiente:

In [22]:
# En la suma de listas solo se concatenan los datos, al contrario si estuviesemos trabajando con un vector 
lista1= (1,2,3)
lista2= (4,5,6)
print(lista1+lista2)

(1, 2, 3, 4, 5, 6)


Seguramente no fue el resultado esperado, al sumar dos listas, creó una nueva lista, más larga, con los elementos de la segunda lista a continuación de la primera.
Obviamente este comportamiento de las listas puede ser muy útil, pero ahora queremos aplicar Python para resolver problemas de álgebra.

## Vectores y Matrices

En programación, se le denomina vector, formación, matriz (en inglés array, del cual surge la mala traducción arreglo),1​ a una zona de almacenamiento contiguo que contiene una serie de elementos del mismo tipo, los elementos de la matriz.2​ Desde el punto de vista lógico una matriz se puede ver como un conjunto de elementos ordenados en fila (o filas y columnas si tuviera dos dimensiones).

En principio, se puede considerar que todas las matrices son de una dimensión, la dimensión principal, pero los elementos de dicha fila pueden ser a su vez matrices (un proceso que puede ser recursivo), lo que nos permite hablar de la existencia de matrices multidimensionales, aunque las más fáciles de imaginar son las de una, dos y tres dimensiones.

Estas estructuras de datos son adecuadas para situaciones en las que el acceso a los datos se realice de forma aleatoria e impredecible. Por el contrario, si los elementos pueden estar ordenados y se va a utilizar acceso secuencial sería más adecuado utilizar una lista, ya que esta estructura puede cambiar de tamaño fácilmente durante la ejecución de un programa, siendo esta última una estructura dinámica (al no tener un tamaño definido). [Fuente](https://es.wikipedia.org/wiki/Vector_(informática))

## Arrays con Numpy
Numpy es una de las librerías matemáticas más usadas en Python y la que da origen a otras aún más sofisticadas. Incorpora algoritmos que permiten resolver operaciones algebraicas en forma **eficiente** porque están precompiladas en C. 
Veamos cómo trabajar con Numpy.

La estructura principal en NumPy es el **array multidimensional homogéneo**.  

Aclaremos un poco:  

**Homogéneo** significa que todos los elementos son del mismo tipo, para nosotros, generalmente serán números, ésto no nos traerá problemas.

**Dimensional o multidimensional** es un término algo confuso ya que se superpone con la definición de dimensión que aprendimos en álgebra! 

A veces se utiliza una nomenclatura que resulta más clara para los elementos de NumPy y en vez de usar la palabra dimensión se utiliza la palabra **axis o eje**. 

Entonces en NumPy:  

- un array de un eje (o dimensión 1 en NumPy)   es lo que en álgebra denominamos **vector**
- un array de 2 ejes (o dimensión 2 en NumPy) es lo que en álgebra definimos como **matriz**
- un array de más ejes (o mayor dimensión en NumPy) es lo que en álgebra se define como **tensor**

Si desde el punto de vista de NumPy todos los vectores tienen un eje (o son de dimensión 1), qué distingue al vector (1,2) del (2,1,4) ?  

La cantidad de elementos que tienen!  

- la cantidad de elementos de (1,2) es 2 y   
- la cantidad de elementos de (2,1,4) es 3

En NumPy la cantidad de elementos se denomina longitud.

### Creación de arrays en NumPy
A diferencia de las listas que comentamos al principio, los arrays deben definirse como tales, vamos a crear un vector, es decir un array con un solo eje o axis o de "dimensión uno".

Para crear el array usamos:

np.array()

y dentro del paréntesis los elementos se enumeran como una secuencia entre corchetes y separados por coma:

np.array([ secuencia de elementos separados por coma ])

Podemos pensar que de esta manera NumPy crea vectores fila.

Creemos el **vector** (1,2,3)

Lo primero que debemos hacer es importar Numpy. Luego declaramos el vector.

In [3]:
#importamos la libreria y le damos un alias u objeto
import numpy as np 

#luego declaramos el vector a trabajar
vector = np.array([1,2,3])

In [4]:
#¿Qué se creó?
vector

array([1, 2, 3])

In [29]:
#Con un print solo se mostrará los datos numericos
print(vector)

[1 2 3]


In [30]:
# si quiero sumar los vectores se sumará cada valor de este, ademas de que puedo colocar un indice y marcar el dato 
# con el que quiero trabajar.
print(vector[1]+vector[1])

4


Ahora vamos a crear una **matriz**.
Desde el punto de vista de NumPy una matriz será una secuencia de vectores, y un vector es una secuencia de números ...


np.array([ [ fila 1 ],[ fila 2 ],...,[ fila n ] ])

In [5]:
# Una matríz es un vector constituido por vectores.
matriz=np.array([[1,2,-1],[3,0,1],[0,2,4],[1,5,3]])
matriz

array([[ 1,  2, -1],
       [ 3,  0,  1],
       [ 0,  2,  4],
       [ 1,  5,  3]])

In [32]:
# Como hicimos anteriormente, para usar un dato seleccionamos la columna y la fila del dato
matriz[1][2]

1

In [6]:
# Con Numpy puedo acortar la escritura y tambien se puede mostrar un elemento de la funcion de la siguiente forma
matriz[1,2]

1

### Describiendo arrays: .ndim, .shape, .size 
* La propiedad .ndim nos indica la cantidad de ejes (o dimensiones) que tiene el array, matrices tienen 2, vectores 1.
* La propiedad .shape nos indica la cantidad de elementos en cada eje, si es una matriz nos indicará la cantidad de filas y de columnas que tiene.
* La propiedad .size nos indica la cantidad de elementos en total que tiene el array

In [33]:
# .ndim en un vector 
vector.ndim

1

In [34]:
# .shape en un vector. Nos indica la cantidad de filas y columnas
vector.shape

(3,)

In [35]:
# .size en nu vector. 
vector.size

3

In [36]:
matriz


array([[ 1,  2, -1],
       [ 3,  0,  1],
       [ 0,  2,  4],
       [ 1,  5,  3]])

In [37]:
#muestra los ejes de la matriz
matriz.ndim

2

In [38]:
#primero la cantidad de filas, luego la cantidad de columnas, muestra la cantidad de esta
matriz.shape

(4, 3)

In [39]:
# .size muestra la cantidad de datos cargados en la matriz
matriz.size

12

### Tensor

Son matrices de 3 dimensiones o vectores constituidos por matrices

In [59]:
tensor=np.array([[[1,2],[2,3],[-1,5]],[[5,3],[0,0],[8,1]],[[5,3],[0,0],[8,1]]])
print(tensor)

[[[ 1  2]
  [ 2  3]
  [-1  5]]

 [[ 5  3]
  [ 0  0]
  [ 8  1]]

 [[ 5  3]
  [ 0  0]
  [ 8  1]]]


In [41]:
tensor.ndim

3

In [42]:
tensor.shape

(3, 3, 2)

In [43]:
tensor.size

18

# Ejercicio para resolver 1
* Crear un vector con los siguientes datos (1,2,3,4,5)
* Mostrar la cantidad de ejes del vector
* Mostrar la cantidad de elementos de cada eje del vector
* Mostrar la cantidad de elementos del vector

In [7]:
import numpy as np

In [8]:
vector=np.array([1,2,3,4,5])

In [9]:
vector.ndim

1

In [10]:
vector.shape

(5,)

In [11]:
vector.size

5

# Ejercicio para resolver 2
* Crear una matriz con los siguientes datos 
((1,2,3),(8,4,6),(7,5,3),(9,5,1))
* Mostrar la cantidad de ejes de la matriz
* Mostrar la cantidad de elementos de cada eje de la matriz
* Mostrar la cantidad de elementos de la matriz

In [12]:
matriz=np.array([[1,2,3],[8,4,6],[7,5,3],[9,5,1]])

In [13]:
matriz.ndim

2

In [14]:
matriz.shape

(4, 3)

In [15]:
matriz.size

12

# Ejercicio para resolver 3
* Crear un tensor con los siguientes datos 
(((1,2,3),(8,4,6)),((7,5,3),(9,5,1)))
* Mostrar la cantidad de ejes del tensor
* Mostrar la cantidad de elementos de cada eje del tensor
* Mostrar la cantidad de elementos ddel tensor

In [64]:
ten = np.array ([[[1,2,3],[8,4,6]],[[7,5,3],[9,5,1]]])
print(ten)

[[[1 2 3]
  [8 4 6]]

 [[7 5 3]
  [9 5 1]]]


In [65]:
ten.ndim

3

In [66]:
ten.shape

(2, 2, 3)

In [69]:
ten.size

12