![imagen](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRv7-9e8oYLYuPJ2mPM3YOlHoKFiHaQCFClWRKVBOzUe1CWABtg5QtluntYIxiHgpYNdw&usqp=CAU)

# Computación Científica

## Situación profesional
Una empresa que brinda el servicio de *streaming* de películas por internet quiere implementar un **Sistema de Recomendación (SR o RS en inglés)** para su usuarios, de tal manera de poder sugerir, dentro de las películas que aún no ha visto, cuál podría ser la que más le gustará.  
Para ello en su plataforma solicitan a cada usuario que califique la película que acaba de ver.  

- La calificación (rating) asume valores de 1 a 5, siendo 1 la peor calificación y 5 la mejor.  
- Se establece el valor 0 para aquellas películas que no han sido calificadas por los usuarios. 

# Algebra en Python: NumPy

La solución de este problema nos obligará a realizar un intenso trabajo **algebraico** tendremos que trabajar con datos, organizados en forma de vectores y matrices y oportunamente deberemos recurrir a operaciones como el producto interno o producto punto para efectuar cálculos de distancias o ángulos como los que ha aprendido en la materia Álgebra.  

Afortunadamente Python cuenta con librerías adecuadas para esta tarea, como NumPy que nos permitirá resolver estas operaciones en forma **eficiente** ya que muchas de sus operaciones están precompiladas en lenguaje C, que es muy veloz a la hora de ejecutar el código, pero contaremos con la facilidad de un lenguaje como Python.

### Creación de arrays en NumPy

Para crear el array usamos:  

**np.array()**  

y dentro del paréntesis los elementos se enumeran como una **secuencia** entre corchetes y separados por coma:  

**np.array([ secuencia de elementos separados por coma ])**

Recordemos que lo primero que debemos hacer es importar Numpy.

In [2]:
# Importamos la libreria
import numpy as np
# Creamos un vector
vector = np.array([1,2,3])
# Mostramos el vector
print(vector)

[1 2 3]


Para crear una **matriz** se hace del mismo modo, só que se debe tener en cuenta que se enumera una lista de vectores dentro de los corchetes.

Recordemos que desde el punto de vista de NumPy una matriz será una secuencia de vectores, y un vector era una secuencia de números ...


np.array([ [ fila 1 ],[ fila 2 ],...,[ fila n ] ])

In [3]:
import numpy as np
matriz = np.array([[1,2],[3,4]])
print(matriz)

[[1 2]
 [3 4]]


### Propiedades: .ndim, .shape, .size 

* ndim: cantidad de ejes. (Dimensiones)
* shape: cantidad de elementos de cada eje. (cantidad de elementos de cada dimensión, forma)
* size: cantidad de elementos de la estructura. (Tamaño, talla)

In [15]:
# Cantidad de ejes del vector
dimension= vector.ndim
# Cantidad de elementos en cada eje
forma= vector.shape
# Cantidad de elementos en el vector
tamaño= vector.size
print(f"dimension: {dimension}")
print(f"forma: {forma}")
print(f"tamaño: {tamaño}")

dimension: 1
forma: (3,)
tamaño: 3


In [14]:
# Cantidad de ejes del vector
dim= matriz.ndim
# Cantidad de elementos en cada eje
form= matriz.shape
# Cantidad de elementos en el vector
tam= matriz.size
print(f"dimension: {dim}")
print(f"forma: {form}")
print(f"tamaño: {tam}")

dimension: 2
forma: (2, 2)
tamaño4


## Operaciones con arrays en NumPy

### Operaciones básicas

Se pueden realizar operaciones entre un vector y un escalar:
* Suma: +
* Resta: -
* Producto: *
* División: /
* Potencia: **
* División entera: //
* Resto de la División: %

In [21]:
# Le sumamos 2 a cada elemento del vector 
import numpy as no
vector = np.array ([1,2,3,6])
print(vector)
print(vector+2)


[1 2 3 6]
[3 4 5 8]


In [19]:
# Le restamos 2 a cada elemento del vector 
import numpy as no
vector = np.array ([1,2,3,6])
print(vector)
print(vector-2)

[1 2 3 6]
[-1  0  1  4]


In [22]:
# Multiplicamos por 2 aa cada elemento del vector 
import numpy as no
vector = np.array ([1,2,3,6])
print(vector)
print(vector*2)

[1 2 3 6]
[ 2  4  6 12]


In [23]:
# dividimos por 2 aa cada elemento del vector 
import numpy as no
vector = np.array ([1,2,3,6])
print(vector)
print(vector/2)

[1 2 3 6]
[0.5 1.  1.5 3. ]


In [24]:
# Dividimos entero por 2 aa cada elemento del vector 
import numpy as no
vector = np.array ([1,2,3,6])
print(vector)
print(vector//2)

[1 2 3 6]
[0 1 1 3]


In [25]:
# Encontramos los restos de la division anterior
import numpy as no
vector = np.array ([1,2,3,6])
print(vector)
print(vector%2)

[1 2 3 6]
[1 0 1 0]


In [26]:
# Elevamos al cuadrado los elementos del vector
import numpy as no
vector = np.array ([1,2,3,6])
print(vector)
print(vector**2)

[1 2 3 6]
[ 1  4  9 36]


### Del mismo modo ocurre con las matrices

In [5]:
# Le sumamos 2 a cada elemento de la matriz
import numpy as no
matriz = np.array ([[1,2],[3,6]])
print(matriz)
print(matriz+2)

[[1 2]
 [3 6]]
[[3 4]
 [5 8]]


In [6]:
# Le restamos 2 a cada elemento de la matriz
import numpy as no
matriz = np.array ([[1,2],[3,6]])
print(matriz)
print(matriz-2)

[[1 2]
 [3 6]]
[[-1  0]
 [ 1  4]]


In [7]:
# lo multiplicamos por 2 a cada elemento de la matriz
import numpy as no
matriz = np.array ([[1,2],[3,6]])
print(matriz)
print(matriz*2)

[[1 2]
 [3 6]]
[[ 2  4]
 [ 6 12]]


In [8]:
# lo dividimos por 2 a cada elemento de la matriz
import numpy as no
matriz = np.array ([[1,2],[3,6]])
print(matriz)
print(matriz/2)

[[1 2]
 [3 6]]
[[0.5 1. ]
 [1.5 3. ]]


In [9]:
# lo dividimos de forma entera por 2 a cada elemento de la matriz
import numpy as no
matriz = np.array ([[1,2],[3,6]])
print(matriz)
print(matriz//2)

[[1 2]
 [3 6]]
[[0 1]
 [1 3]]


In [10]:
# mostramos el resto de la division entera por 2 a cada elemento de la matriz
import numpy as no
matriz = np.array ([[1,2],[3,6]])
print(matriz)
print(matriz%2)

[[1 2]
 [3 6]]
[[1 0]
 [1 0]]


In [11]:
# lo elevamos al cuadrado a cada elemento de la matriz
import numpy as no
matriz = np.array ([[1,2],[3,6]])
print(matriz)
print(matriz**2)

[[1 2]
 [3 6]]
[[ 1  4]
 [ 9 36]]


También se pueden realizar operaciones entre un vector, pero hay que tener en cuenta que si desea sumar o restar vectores con distinta cantidad de elementos, dará error.

In [29]:
# Importamos la libreria y creamos dos vectores
import numpy as np
d1= np.array ([1,2,3])
d2= np.array([4,5,6])
print(d1)
print(d2)
print(d1+d2)

[1 2 3]
[4 5 6]
[5 7 9]


In [30]:
import numpy as np
d1= np.array ([1,2,3])
d2= np.array([4,5,6])
print(d1)
print(d2)
print(d1-d2)

[1 2 3]
[4 5 6]
[-3 -3 -3]


In [32]:
import numpy as np
d1= np.array ([1,2,3])
d2= np.array([4,5,6])
print(d1)
print(d2)
print(d1*d2)

[1 2 3]
[4 5 6]
[ 4 10 18]


In [31]:
import numpy as np
d1= np.array ([1,2,3])
d2= np.array([4,5,6])
print(d1)
print(d2)
print(d1/d2)

[1 2 3]
[4 5 6]
[0.25 0.4  0.5 ]


se puede realizar el mismo proceso con matrices

In [34]:
# Importamos la libreria y creamos dos matrices
import numpy as np
m1 = np.array([[7, 4],[0, 3], [1,3]])
m2 = np.array([[1, 2],[3, 6], [8,7]])
print(m1)
print(m2)
print(m1+m2)

[[7 4]
 [0 3]
 [1 3]]
[[1 2]
 [3 6]
 [8 7]]
[[ 8  6]
 [ 3  9]
 [ 9 10]]


In [35]:
import numpy as np
m1 = np.array([[7, 4],[0, 3], [1,3]])
m2 = np.array([[1, 2],[3, 6], [8,7]])
print(m1)
print(m2)
print(m1-m2)

[[7 4]
 [0 3]
 [1 3]]
[[1 2]
 [3 6]
 [8 7]]
[[ 6  2]
 [-3 -3]
 [-7 -4]]


In [36]:
import numpy as np
m1 = np.array([[7, 4],[0, 3], [1,3]])
m2 = np.array([[1, 2],[3, 6], [8,7]])
print(m1)
print(m2)
print(m1*m2)

[[7 4]
 [0 3]
 [1 3]]
[[1 2]
 [3 6]
 [8 7]]
[[ 7  8]
 [ 0 18]
 [ 8 21]]


In [37]:
import numpy as np
m1 = np.array([[7, 4],[0, 3], [1,3]])
m2 = np.array([[1, 2],[3, 6], [8,7]])
print(m1)
print(m2)
print(m1/m2)

[[7 4]
 [0 3]
 [1 3]]
[[1 2]
 [3 6]
 [8 7]]
[[7.         2.        ]
 [0.         0.5       ]
 [0.125      0.42857143]]


## Funciones universales

- Raíz cuadrada: np.sqrt()
- Funciones trigonométricas como sin(), cos(), tan()
- Exponenciales

In [13]:
# Ejemplo de raiz cuadrada
import numpy as np
a = np.array([9,16,25,36])
b = np.sqrt(a)
print(a)
print(b)

[ 9 16 25 36]
[3. 4. 5. 6.]


### Producto interno o producto punto de vectores

El producto interno de dos vectores puede realizarse de dos maneras:  

- con el operador @, vector1 @ vector2  
- con la función:  np.dot(vector1, vector2)

Veamos:

In [4]:
# Con vectores
import numpy as np
d1= np.array ([1,2,3])
d2= np.array([4,5,6])
print(d1)
print(d2)
print(d1@d2)

[1 2 3]
[4 5 6]
32


In [5]:
import numpy as np
d1= np.array ([1,2,3])
d2= np.array([4,5,6])
print(d1)
print(d2)
print(np.dot(d1,d2))

[1 2 3]
[4 5 6]
32


In [20]:
# Se puede calcular el producto interno de una matriz solo si esta es cuadrada
import numpy as np
m1 = np.array([[7, 4],[0, 3]])
m2 = np.array([[1, 2],[3, 6]])
print(m1)
print(m2)
print(m1@m2)

[[7 4]
 [0 3]]
[[1 2]
 [3 6]]
[[19 38]
 [ 9 18]]


### Módulo o norma de un vector

En álgebra se define el Módulo o norma de un vector como un número positivo que representa la longitud del mismo.

Si el vector es $ u=(u_1,u_2,...,u_n)$

Su módulo o norma se calcula como:

$$||u||=\sqrt[]{u^2_1+u^2_2+...+u^2_n}$$  

Si lo pensamos un poco, calcular la norma de un vector con los métodos de programación tradicionales requiere efectuar algún loop recorriendo todos los elementos del vector, elevándolos al cuadrado, sumándolos a un acumulador y luego de recorrer todo el vector deberíamos calcular su raíz cuadrada.  

Un poco pesado, por suerte pensando algebraicamente y usando NumPy tenemos opciones muy sencillas que nos permitirán focalizarnos en las operaciones matemáticas y no en la programación en sí. 




El módulo de un vector se podía calcular también como la raíza cuadrada del producto interno del vector con sí mismo:

$$ ||u||=\sqrt[]{u . u} $$


Entonces podríamos calcular el módulo del vecto v1 como:

In [21]:
# Si quisieramos sacar el modulo de un vector deberia realizarse todo este procedimiento con la programacion antigüa
import numpy as np
v1=np.array([2,0,1])
res=0
for x in v1:
    res = res + (x**2)
print(res)
print(np.sqrt(res))

5
2.23606797749979


In [9]:
# Gracias a las librerias, podemos simplificar todo el paso anterior de la siguiente forma
import numpy as np 
vec= np.array([2,0,1])
np.sqrt(vec@vec)

2.23606797749979

Bastante más sencillo, no es cierto?

Pero además, dentro de NumPy existe una librería dedicada a operaciones específicas de álgebra lineal denominada **linalg**, y entre ellas se encuentra el cáclulo del módulo o norma de un vector, así que podemos efectuar el cálculo en forma más elegante y legible para quien lee el código:


In [11]:
import numpy as np 
vec= np.array([2,0,1])
np.linalg.norm(vec)

2.23606797749979

### Distancia entre dos vectores o dos puntos

En álgebra se define la distancia (euclídea) entre dos puntos o entre 2 vectores como el módulo o norma de su diferencia:  

distancia(u,v) = ||u-v||  

Se anima a calcular la distancia entre los vectores v1 y v2 que definimos con anterioridad?

Resuelva el problema primero manualmente con papel y lápiz ... y luego en la celda siguiente

In [14]:
import numpy as np
v1=np.array([2,0,1])
v2=np.array([5,6,4])
np.linalg.norm(v1-v2)

7.3484692283495345

## EJERCICIOS

Supongamos que tenemos la intención de crear un **Sistema de Recomendaciones** para los clientes de nuestro servicio de streaming de películas.  

Para ello, decidimos recabar información de nuestros clientes, por ejemplo le solicitamos que califique qué tanto le gustó cada película después de que la vio.  

Elaboramos un ranking de 1 a 5 siendo 1 que le gustó poco y 5 que le gustó muchísimo.  

Después de un tiempo tendremos el puntaje asignado a muchas películas por muchos clientes.  
Supongamos que nuestros clientes son A,B,C,D, etc y las películas son P1,P2, P3, nuestra información podría verse como en la siguiente tabla.


Nuestro objetivo es determinar si le recomendamos o no al cliente D la P4.  

Nuestra hipótesis es que el gusto del cliente D será similar al del cliente que haya calificado más parecido a D las películas P1, P2 y P3, es decir al cliente más cercano a D considerando sólo las películas de 1 a 3.  

Entonces crearemos un vector para cada cliente con las calificaciones que dio para las películas 1 a 3 y calcularemos la distancia entre el vector del cliente D y cada uno de los otros clientes. 

Esto nos permitirá determinar cuál de los clientes A, B o C es el más cercano a D, y asumiremos que el cliente D tendrá una calificación de P4 parecida al del más cercano a él.


In [23]:
# Cree aquí los vectores considerando sólo las películas P1 a P3 para los cuatro clientes
import numpy as np
ca=np.array([5,1,3])
cb=np.array([3,5,4])
cc=np.array([1,3,5])
cd=np.array([4,2,1])

In [25]:
#Calcule la distancia entre el vector del cliente D y el cliente A
dda=np.linalg.norm(cd-ca)
dda

2.449489742783178

In [18]:
#Calcule la distancia entre el vector del cliente D y el cliente B
ddb=np.linalg.norm(cd-cb)
ddb

4.358898943540674

In [19]:
#Calcule la distancia entre el vector del cliente D y el cliente C
ddc=np.linalg.norm(cd-cc)
ddc

5.0990195135927845

Cuál es el cliente más cercano a C4? En base a esta cercanía, cree que la P4 le gustará o no a C4?

# ¿Podemos automatizar el ejercicio anterior? 

In [8]:
import numpy as np
# Creamos una matriz con los datos de los clientes que vieron la pelicula 4
matriz = np.array ([[5,1,3],[3,5,4],[1,3,5]])
# Creamos un vector con los datos del cliente que no vio la pelicula 4
vector= np.array([4,2,1])
# Creamos un vector con las respuestas a la pelicula 4
puntos = np.array([1,4,3])
# Comparo el vector con cada fila de la matriz con un for
norma = 0
menor = 100
cliente = 0 
fila=0
for x in matriz:
    norma = np.linalg.norm(vector-x)
    if norma < menor: 
        menor=norma
        cliente = fila
    fila = fila+1
if puntos [cliente] > 3:
    print("si le va a gustar la pelicula 4")
else:
    print("no le va a gustar la pelicula 4")

no le va a gustar la pelicula 4


Rta: La menor distancia es con el Cliente1, como al Cliente1 no le gustó P4 ya que la calificó con 1 es posible al C4 tampoco le guste.

### Producto vectorial de dos vectores o producto cruz

![](https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Cross_product_parallelogram.svg/330px-Cross_product_parallelogram.svg.png)
Se puede utilizar la función np.cross(v1,v2)

Video que explica como calcular de forma manual el producto cruz: [Video]("https://www.youtube.com/watch?v=io1vem2CmGc")

In [27]:
#Importamos la librería numpy y creamos dos vectores
import numpy as np
v1=np.array([-3,-2,+5])
v2=np.array([6,-10,-1])

# Veamos el resultado del producto interno de los vectores
interno=np.linalg.norm(v1-v2)
interno

13.45362404707371

In [29]:
#Importamos la librería numpy y creamos dos vectores
import numpy as np
v1=np.array([1,2,3])
v2=np.array([2,8,4])

# Veamos el resultado del producto interno de los vectores
inter=np.linalg.norm(v1-v2)
inter

6.164414002968976

In [30]:
#Importamos la librería numpy y creamos dos vectores
import numpy as np
v1=np.array([2,0,1])
v2=np.array([1,-1,3])

# Veamos el resultado del producto interno de los vectores
prod=np.linalg.norm(v1-v2)
prod

2.449489742783178