![imagen](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRv7-9e8oYLYuPJ2mPM3YOlHoKFiHaQCFClWRKVBOzUe1CWABtg5QtluntYIxiHgpYNdw&usqp=CAU)

# Computación Científica

## Selección de elementos de un array (vector, matriz, tensor)

### IMPORTANTE: 
lo primero que debemos saber al respecto es que en Python **los elementos de una secuencia se comienzan a enumerar o _indexar_ desde 0, no desde 1**.  

Esto significa que **el primer elemento de una secuencia ocupa la posición 0**

Así por ejemplo si tenemos el vector $$ w=(a,b,c) $$  
su **primer elemento es $a$** y ocupa la **posicion 0** dentro del vector $w$

Lo mismo ocurre para las matrices u otros arreglos. 

Por ejemplo en la matriz 
$$M=\begin{bmatrix} 3 & 1 & -1 & 4\\ 2 & 5 & 1 & 2\\ 0 & 2 & 4 & 1 \end{bmatrix}$$

Las filas (y también las columnas) se enumeran desde 0.   
Es decir que la primer fila es la fila 0:  
$$fila \, 0=\begin{bmatrix} 3 & 1 & -1 & 4 \end{bmatrix}$$  
Y la columna 0 es: 
$$columna\, 0=\begin{bmatrix} 3 \\ 2 \\ 0  \end{bmatrix}$$  

El 3 es "primer elemento de la matriz" y ocupa la posición (0,0): fila 0 y columna 0.

Vamos a crear dos vectores y una matriz:


In [1]:
import numpy as np
u=np.array([1,2,3])
v=np.array([2,0,-4])
M=np.array([[3,1,-1,4],[2,5,1,2],[0,2,4,1]])

### Uso de **[     ]** con vectores o arrays de un solo eje (unidimensionales)

Para acceder a una posición dentro de un array se utilizan los corchetes 

**[ posición del elemento en cada eje separado por comas ]**  

Así por ejemplo si deseamos acceder al primer elemento de un vector como u=(1,2,3), como u tiene sólo un eje bastará escribir:  
u[0]

In [2]:
# Escribra aquí su código
u[0]

1

Obtenga el tercer elemento del vector u

In [3]:
# Escribra aquí su código
u[2]

3

Vamos a cargar un vector un poco más largo para que se pondan de manifiesto algunas características:  

$$ w=(10,20,30,40,50,60,70,80,90,100)$$


In [4]:
# Escriba aquí su código para crear el vector w 
w=np.array([10,20,30,40,50,60,70,80,90,100])
# muéstrelo
print(w)

[ 10  20  30  40  50  60  70  80  90 100]


In [5]:
# Obtenga el primer elemento
w[0]

10

In [6]:
# Obtenga el cuarto elemento
w[3]

40

In [7]:
# Obtenga el décimo elemento
w[9]

100

### Uso de : con vectores o arrays de un solo eje  (unidimensionales)

Como ya estará pensando, debería haber alguna forma de poder obtener varios elementos juntos, por ejemplo los primeros 5 elementos o cosas por el estilo.   
Para ésto se utilizan los dos puntos **:**

Observe cómo funcionan los **:** con nuestro conocido vector  

$$ w=(10,20,30,40,50,60,70,80,90,100)$$

In [6]:
#escriba el código que carga el vector w
𝑤=np.array([10,20,30,40,50,60,70,80,90,100])
#muestre desde la tercera posición a la quinta inclusive
w[2:5]

array([30, 40, 50])

Como puede observar w[2:5] , devolvió los elementos con índices 2,3,y 4.  
Observe que **no** incluyó al elemento con índice 5. 

Podríamos pensarlo así:  

w[ desde este índice : hasta este índice pero **SIN** incluírlo ]


Le recuerdo quién era w  

$$ w=(10,20,30,40,50,60,70,80,90,100)$$

Escriba el código que devuelva [ 60,70,80,90 ]

In [9]:
# Escriba aquí su código:
w[5:9]

array([60, 70, 80, 90])

Otro, por las dudas ...
Escriba el código que devuelva [20,30,40,50,60]

In [10]:
# Escriba aquí su código:
w[1:6]

array([20, 30, 40, 50, 60])

Si se omite el valor "desde" asume que es desde el índice 0, es decir desde el primer elemento.


In [11]:
# Escriba aquí su código:
w[:4]

array([10, 20, 30, 40])

debería ser exactamente lo mismo que

In [12]:
# Escriba aquí su código:
w[0:4]

array([10, 20, 30, 40])

Obtenga los primeros seis elementos de w

In [14]:
# Escriba aquí su código
w[:6]

array([10, 20, 30, 40, 50, 60])

Si se omite el valor "hasta", asume que es hasta el último elemento.
Qué obtendríamos con  w[5: ]?

In [15]:
# Escriba aquí su código:
w[5:]

array([ 60,  70,  80,  90, 100])

Escriba el código para obtener los números desde el 40 hasta el 100, le recuerdo cómo era  

$$ w=(10,20,30,40,50,60,70,80,90,100)$$



In [16]:
# Escriba aquí su código
w[3:]

array([ 40,  50,  60,  70,  80,  90, 100])

Además puede indexarse contando desde el final ... usando índices negativos

In [19]:
# Escriba aquí su código:
w [2:-1]

array([30, 40, 50, 60, 70, 80, 90])

In [8]:
# Escriba aquí su código:
w[2:-2]

array([30, 40, 50, 60, 70, 80])

In [13]:
# Escriba aquí su código:
w[-2:]

array([ 90, 100])

Cómo haría para obtener los 3 últimos elementos?

In [12]:
# Escriba aquí su código
w[-3:]

array([ 80,  90, 100])

Cómo haría para obtener los primeros 3 elementos?

In [38]:
# Escriba aquí su código
w[:-7]

array([10, 20, 30])

In [15]:
# o de otra forma
w[:3]

array([10, 20, 30])

Qué le parece que sería el resultado de w[ : ]?

In [39]:
# Escriba aquí su código
# Sirve para mostrar todo el vector, se puede solucionar solamente poniendo la "w" sola
w[:]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

Tenga presente este resultado cuando investiguemos las matrices a continuación.

Hasta ahora hemos obtenido elementos que son contiguos. Cómo podríamos hacer si quisiéramos elementos que no son contiguos?  
Supongamos que queremos el primer, tercer y quinto elementos de w.  

1. Primero deberíamos crear un array con los índices que deseáramos obtener
2. Luego pasaríamos estos índices como parámetro

In [45]:
# Escriba aquí su código:
indices= np.array([0,2,4])
w[indices]

array([10, 30, 50])

Obtenga los elementos que se encuentran en las posiciones segunda, cuarta y octava de w

In [46]:
# Escriba aquí su código
indice=np.array([1,3,7])
w[indice]

array([20, 40, 80])

Por supuesto que no era necesario crear primero el array de índices, hubiera bastado con hacer:

In [47]:
# Escriba aquí su código:
w[[1,3,7]]

array([20, 40, 80])

### Uso de **[     ]** con matrices o arrays de 2 ejes (bidimensionales)

Para acceder a una posición dentro de un array se utilizan los corchetes 

**[ posición del elemento en cada eje separado por comas ]**  

M[0:3,1]

Para el caso de las matrices es decir los arrays con 2 ejes deberemos indicar la posición del elemento en cada uno de los ejes.  
$$M=\begin{bmatrix} 3 & 1 & -1 & 4\\ 2 & 5 & 1 & 2\\ 0 & 2 & 4 & 1 \end{bmatrix}$$

**M[ fila, columna ]**  
(recuerde que a diferencia del álgebra, aquí el primer elemento es el 0)


Para acceder al primer elemento, el número 3, deberemos indicar que está en la fila 0 y en la columna 0:  

**M[0,0]** 



In [52]:
# Escriba aquí su código:
# Primer elemento de la matriz
M[0,0]

3

In [16]:
# Para traer el dato de la fila 2 columna 2 se escribe el siguiente codigo
M[1,1]

5

Obtenga el 5 de la matriz M

In [55]:
# Escriba aquí su código
M[1,1]

5

Supongamos que queremos obtener toda una una fila de M, digamos la primer fila (la fila número 0).  
Deberíamos indicar algo como esto:  
M[ número de fila deseada, todas las columnas]

Entonces para obtener la fila 0 podríamos escribir:

In [59]:
# Escriba aquí su código:
M[0,:]

array([ 3,  1, -1,  4])

Que es una nomenclatura bastante explícita, también soporta una nomenclatura como la siguiente, pero no la recomendamos.

In [60]:
# Funciona igual que lo anterior
M[0,]

array([ 3,  1, -1,  4])

Cómo obtendría la segunda fila?

In [58]:
# Escriba aquí su código
M[1,]             

array([2, 5, 1, 2])

In [61]:
# De otra forma
M[1,:]

array([2, 5, 1, 2])

Cómo obtendría la última fila, sin importar cuántas filas tuviera la matriz?

In [17]:
# Escriba aquí su código
M[-1,:]

array([0, 2, 4, 1])

Cómo obtendría las dos primeras filas?

In [18]:
# Escriba aquí su código
M[0:2,:]

array([[ 3,  1, -1,  4],
       [ 2,  5,  1,  2]])

In [19]:
# De esta forma se obtiene lo mismo 
M[:2,:]

array([[ 3,  1, -1,  4],
       [ 2,  5,  1,  2]])

La primer y tercer filas?

In [20]:
# Para realizar esto se debe crear un array
M[[0,2],:]

array([[ 3,  1, -1,  4],
       [ 0,  2,  4,  1]])

In [76]:
# Del mismo modo 
indices=np.array([0,2],)
M[indices]

array([[ 3,  1, -1,  4],
       [ 0,  2,  4,  1]])

Ahora practiquemos un poco con las columnas:  

$$M=\begin{bmatrix} 3 & 1 & -1 & 4\\ 2 & 5 & 1 & 2\\ 0 & 2 & 4 & 1 \end{bmatrix}$$
Obtenga la primer columna de M

In [78]:
# Escriba aquí su código
# No se pueden eliminar los : cuando se tienen columnas
M[:,0]

array([3, 2, 0])

**Nota:** Observe que no presenta el resultado como una "columna", sino como un array de un solo eje.

La segunda y tercer columnas?

In [84]:
# Escriba aquí su código
M[:,1:3]

array([[ 1, -1],
       [ 5,  1],
       [ 2,  4]])

La segunda y la cuarta columnas?

In [86]:
# Escriba aquí su código
M[:,[1,3]]

array([[1, 4],
       [5, 2],
       [2, 1]])

## Arrays especiales

In [1]:
# Crer una matriz de 3 filas por 4 columnas llena de 1:
import numpy as np
N=np.ones((3,4))
N

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [2]:
# Asigne un cero a la celda 0,0:
N[0,0]=0
N

array([[0., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [3]:
# Asigne un cero a la celda 0,3:
N[0,3]=0
N

array([[0., 1., 1., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
# Asigne un cero a la celda 2,1:
N[2,1]=0
N

array([[0., 1., 1., 0.],
       [1., 1., 1., 1.],
       [1., 0., 1., 1.]])

In [5]:
# multiplique todos los valores de la fila 1 por 2:
N[1,:]=2*N[1,:]
N

array([[0., 1., 1., 0.],
       [2., 2., 2., 2.],
       [1., 0., 1., 1.]])

In [6]:
# multiplique todos los valores de la fila 2 por 3:
N[2,:]=3*N[2,:]
N

array([[0., 1., 1., 0.],
       [2., 2., 2., 2.],
       [3., 0., 3., 3.]])

In [7]:
# multiplique todos los valores de la fila 0 por 4:
N[0,:]=4*N[0,:]
N

array([[0., 4., 4., 0.],
       [2., 2., 2., 2.],
       [3., 0., 3., 3.]])