# SP01 Ejercicios Vectores 1

In [5]:
# Importar las librería Numpy
import numpy as np

## Ej 1
Cree el siguiente array de Numpy y llámelo v1

$$ v1=[1,2,3,4,5,6,7,8,9,10, ..., 50] $$

In [6]:
# Escriba aquí su código
v1= np.arange(1,51,1)
v1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

## Ej 2
Cree el siguiente array de Numpy y llámelo v2

$$ v2=[2,4,6,8,10,...,100] $$

In [15]:
# Escriba aquí su código
v2=np.arange(2,101,2)
v2

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

## Ej 3
Cree el siguiente array de Numpy y llámelo v3

$$ v3=[3,6,9,12,...,150] $$

In [14]:
# Escriba aquí su código
v3=np.arange(3,151,3)
v3

array([  3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,  39,
        42,  45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,  78,
        81,  84,  87,  90,  93,  96,  99, 102, 105, 108, 111, 114, 117,
       120, 123, 126, 129, 132, 135, 138, 141, 144, 147, 150])

## Ej 4

Calcule el módulo o norma de los vectores anteriores, llame a esto valores mod_v1 mod_v2 y mod_v3

In [20]:
# Escriba aquí su código
mod_v1= np.linalg.norm(v1)
mod_v1

207.18349355100662

In [19]:
# Escriba aquí su código
mod_v2=np.linalg.norm(v2)
mod_v2

414.36698710201324

In [21]:
# Escriba aquí su código
mod_v3=np.linalg.norm(v3)
mod_v3

621.5504806530198

## Ej 5

Cree un vector que tenga la misma cantidad de elementos que los anteriores y que esté formado todo por números veinte, llámelo v_veintes.    

- Cuál de los vectores anteriores es más cercano a v_veintes?   
- Guarde el valor de la menor distancia en una variable llamada: min_dist 
- Cuál es el vector más lejaano a v_veintes? 
- Guarde este valor en nmax_dist

In [26]:
# Escriba aquí su código
v_veintes=np.full(len(v1),20)
v_veintes

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [25]:
# forma de ver cuantos elementos tiene un vector o matriz
len(v1)

50

In [30]:
v1.size

50

In [33]:
# Escriba aquí su código
dv1v=np.linalg.norm(v1-v_veintes)
dv1v

109.20164833920778

In [34]:
# Escriba aquí su código
dv2v=np.linalg.norm(v2-v_veintes)
dv2v

299.4995826374387

In [32]:
# Escriba aquí su código
dv3v=np.linalg.norm(v3-v_veintes)
dv3v

503.3140172894055

In [47]:
# Otra forma de encontrar minimos y maximos 
min_dist=min(dv1v,dv2v,dv3v)
print(min_dist)
nmax_dist=max(dv1v,dv2v,dv3v)
print(nmax_dist)

109.20164833920778
503.3140172894055


In [36]:
# Escriba aquí su código
min_dist=np.linalg.norm(v1-v_veintes)
max_dist=np.linalg.norm(v3-v_veintes)

## Respuestas

In [37]:
v1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [38]:
v2

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [39]:
v3

array([  3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,  39,
        42,  45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,  78,
        81,  84,  87,  90,  93,  96,  99, 102, 105, 108, 111, 114, 117,
       120, 123, 126, 129, 132, 135, 138, 141, 144, 147, 150])

In [40]:
mod_v1

207.18349355100662

In [41]:
mod_v2

414.36698710201324

In [42]:
mod_v3

621.5504806530198

In [43]:
v_veintes

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [44]:
min_dist

109.20164833920778

In [45]:
max_dist

503.3140172894055